### ISSUE TITLE
Question: whatever reference/discussion of the three-term LQR cost function

### ISSUE THREAD

**Issue by hurak** [JuliaControl/RobustAndOptimalControl.jl#103]
Among the provided functions there is also the `lqr3` function. Its docstring reads: 
> Calculate the feedback gain of the discrete LQR cost function augmented with control differences. 

Could you please direct me to any discussion of this extension in the literature? Or I would be grateful for whatever discussion of this.

It is quite common to penalize the increments of control in the quadratic cost and not the control itself when using MPC, but I have never encountered the three-term version.

Thanks.

**Comment by baggepinnen** [comment]
I added the function `dare3` in order to easily compute the cost-to-go for an MPC controller with a penalty term on control increments. The `dare3` function allows the user to specify the cost function by means of and additional matrix that weights the quadratic penalty on control increments, rather than having to manually assemble the cost matrices that would do the same for a model augmented with additional state variables in order to compute control increments in the model. The `lqr3` simply returns the associated feedback gain, I use this feedback gain to test the correctness of my implementation of MPC controllers. 

`dare3` is tested here
https://github.com/JuliaControl/RobustAndOptimalControl.jl/blob/master/test/test_lqg.jl#L394C1-L402C39
